### ISSUE TITLE
python_package fails with a user specified

### ISSUE THREAD

**Issue by dmerrick** [poise/poise-python#18] opened 2015-12-03 20:19 UTC
```
python_package 'hipsaint' do
  user  node[:nagios][:user]
  group node[:nagios][:group]
end
```

results in:

```
STDERR: The directory '/root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/root/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
```

Seems like `$HOME` needs to be set.

Not sure if https://github.com/poise/poise-python/pull/12 will fix it.

**Comment by coderanger** [comment] 2015-12-03 23:32
Duplicate of #12

**Closed by coderanger** 2015-12-03 23:32 UTC
