### ISSUE TITLE
can't modify frozen Array on Chef 14.3.37-1 

### ISSUE THREAD

**Issue by shanewarner** [poise/poise-python#120] opened 2018-07-11 18:44 UTC
Update from chef 14.2.x to 14.3.37-1 now yields the following:

    amazon-ebs: ================================================================================
    amazon-ebs: Recipe Compile Error in /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/poise-python/libraries/default.rb
    amazon-ebs: ================================================================================
    amazon-ebs:
    amazon-ebs: FrozenError
    amazon-ebs: -----------
    amazon-ebs: can't modify frozen Array
    amazon-ebs:
    amazon-ebs: Cookbook Trace:
    amazon-ebs: ---------------
    amazon-ebs:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:220:in `included'
    amazon-ebs:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise/resource.rb:51:in `include'
    amazon-ebs:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise/resource.rb:51:in `poise_subresource_container'
    amazon-ebs:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise.rb:93:in `block in Poise'
    amazon-ebs:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime.rb:34:in `include'
    amazon-ebs:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime.rb:34:in `<class:Resource>'
    amazon-ebs:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime.rb:33:in `<module:PythonRuntime>'
    amazon-ebs:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime.rb:25:in `<module:Resources>'
    amazon-ebs:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime.rb:22:in `<module:PoisePython>'
    amazon-ebs:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime.rb:21:in `<top (required)>'
    amazon-ebs:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources.rb:19:in `<top (required)>'
    amazon-ebs:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/poise-python/files/halite_gem/poise_python/cheftie.rb:17:in `<top (required)>'
    amazon-ebs:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/poise-python/libraries/default.rb:19:in `<top (required)>'
    amazon-ebs:
    amazon-ebs: Relevant File Content:
    amazon-ebs: ----------------------
    amazon-ebs: /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:
    amazon-ebs:
    amazon-ebs: 213:                @container_default
    amazon-ebs: 214:              end
    amazon-ebs: 215:            end
    amazon-ebs: 216:
    amazon-ebs: 217:            def included(klass)
    amazon-ebs: 218:              super
    amazon-ebs: 219:              klass.extend(ClassMethods)
    amazon-ebs: 220>>             klass.const_get(:HIDDEN_IVARS) << :@subcontexts
    amazon-ebs: 221:              klass.const_get(:FORBIDDEN_IVARS) << :@subcontexts
    amazon-ebs: 222:            end
    amazon-ebs: 223:          end
    amazon-ebs: 224:
    amazon-ebs: 225:          extend ClassMethods
    amazon-ebs: 226:        end
    amazon-ebs: 227:      end
    amazon-ebs: 228:    end
    amazon-ebs: 229:  end
    amazon-ebs:
    amazon-ebs: Additional information:
    amazon-ebs: -----------------------
    amazon-ebs:       Ruby objects are often frozen to prevent further modifications
    amazon-ebs:       when they would negatively impact the process (e.g. values inside
    amazon-ebs:       Ruby's ENV class) or to prevent polluting other objects when default
    amazon-ebs:       values are passed by reference to many instances of an object (e.g.
    amazon-ebs:       the empty Array as a Chef resource default, passed by reference
    amazon-ebs:       to every instance of the resource).
    amazon-ebs:
    amazon-ebs:       Chef uses Object#freeze to ensure the default values of properties
    amazon-ebs:       inside Chef resources are not modified, so that when a new instance
    amazon-ebs:       of a Chef resource is created, and Object#dup copies values by
    amazon-ebs:       reference, the new resource is not receiving a default value that
    amazon-ebs:       has been by a previous instance of that resource.
    amazon-ebs:
    amazon-ebs:       Instead of modifying an object that contains a default value for all
    amazon-ebs:       instances of a Chef resource, create a new object and assign it to
    amazon-ebs:       the resource's parameter, e.g.:
    amazon-ebs:
    amazon-ebs:       fruit_basket = resource(:fruit_basket, 'default')
    amazon-ebs:
    amazon-ebs:       # BAD: modifies 'contents' object for all new fruit_basket instances
    amazon-ebs:       fruit_basket.contents << 'apple'
    amazon-ebs:
    amazon-ebs:       # GOOD: allocates new array only owned by this fruit_basket instance
    amazon-ebs:       fruit_basket.contents %w(apple)
    amazon-ebs:
    amazon-ebs:
    amazon-ebs: System Info:
    amazon-ebs: ------------
    amazon-ebs: chef_version=14.3.37
    amazon-ebs: platform=ubuntu
    amazon-ebs: platform_version=16.04
    amazon-ebs: ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
    amazon-ebs: program_name=/usr/bin/chef-solo
    amazon-ebs: executable=/opt/chef/bin/chef-solo

**Comment by coderanger** [comment] 2018-07-11 18:49
The problem is from Poise itself, and will be fixed shortly.

**Closed by coderanger** 2018-07-11 18:49 UTC
