### ISSUE TITLE
No candidate version available for setuptools

### ISSUE THREAD

**Issue by rem7** [poise/poise-python#28] opened 2016-01-20 20:33 UTC
Seems like something is breaking this cookbook? 

I'm getting the same issue that is shown by the TravisCI Failed build
```
Error executing action `install` on resource 'python_package[setuptools]'
```
https://travis-ci.org/poise/poise-python/jobs/103535517

The same commit over the past 4 days was passing so I don't think its directly related to poise-python but something in chef or ubuntu?

I'm using Ubuntu 14.04.2 LTS
Chef 12.5.1-1 

Any ideas what could be causing the issue?

**Comment by coderanger** [comment] 2016-01-20 20:36
We've been tracking it on a few other tickets too, but having one people can find is good. The issue is Pip 8.0 released yesterday broke some of my hacks. Fixes are in progress, no known workarounds (that actually work correctly, also working on that) at this time.

**Comment by rem7** [comment] 2016-01-20 20:41
thanks for the quick response :+1: 
Is there an easy way to pin down the pip version?

**Comment by coderanger** [comment] 2016-01-20 21:10
Not currently, or at least the way that is supposed to work isn't working anymore either.

**Comment by mjuszczak** [comment] 2016-01-20 21:17
Also experiencing this. Thanks for your work @coderanger.

**Comment by chewi** [comment] 2016-01-20 23:00
I was tearing my hair out for hours today as this happened on the first day I was trying out poise-python in production. I thought it was something to do with our HTTP proxy. Evidently not.

I have grabbed the latest master with these new fixes as of 43282e75693ae8b03fabe61cf905b9df569421c4 and built the cookbook with rake. Now it gets past setuptools and fails on beaver. It looks a little bit like #26 as it fails on `/usr/bin/python2.7 - list --outdated beaver\=\=31` but I'm not calling the resource like that. Here are the details from the debug output.

```ruby
python_package("beaver") do
  action [:install]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  package_name "beaver"
  version "31"
  timeout 900
  declared_type :python_package
  cookbook_name :beaver
  recipe_name "default"
  parent_python python_runtime[beaver]
end
```

**Comment by coderanger** [comment] 2016-01-20 23:01
Some fixes at in master now, but still working on getting all the tests passing before I release.

**Comment by chewi** [comment] 2016-01-20 23:10
Please check with beaver before you do release as I have already tried master at the time of your comment above.

**Comment by coderanger** [comment] 2016-01-20 23:12
@chewi Pleaes include the actual error.

**Comment by chewi** [comment] 2016-01-20 23:19
https://gist.github.com/chewi/384cf9f8878065742efc

**Comment by coderanger** [comment] 2016-01-21 00:22
Confirmed ^^ is a general issue with the `pip outdated` hack script. Working on it now.

**Comment by coderanger** [comment] 2016-01-21 01:48
Took longer than hoped, but a fix is in master and building on travis now.

**Comment by coderanger** [comment] 2016-01-21 04:44
Version 1.2.1 released with fixes.

**Closed by coderanger** 2016-01-21 04:44 UTC

**Comment by rem7** [comment] 2016-01-21 04:57
thanks so much for fixing this!

**Comment by mjuszczak** [comment] 2016-01-21 05:03
Thank you!

**Comment by AlexBevan** [comment] 2016-01-26 17:32
Cheers, now works like a charm.
